package security

import (
	"os"
	"path/filepath"
)

// GenerateEphemeralEnv creates a safe development .env file to override production secrets
func GenerateEphemeralEnv(worktreePath string) error {
	envPath := filepath.Join(worktreePath, ".env")

	ephemeralContent := `# EPHEMERAL DEVELOPMENT ENV
# Generated by Diffless Lockdown
# Production API secrets have been explicitly stripped for Zero-Trust AI containment.

DEV_MODE=true
DB_MOCK_ENABLED=true
API_KEY_MOCK=sandbox_diff_dev_key_ephemeral_x999
`
	// 0600 ensures only the owner can read/write the .env file
	return os.WriteFile(envPath, []byte(ephemeralContent), 0600)
}
